language: go
go:
  - master

install:
  - go get github.com/gohugoio/hugo    # consume time 70.85s

before_script:
  - rm -rf public 2> /dev/null

# script - run the build script
script:
  - hugo

addons:
  ssh_known_hosts: orthen.net

before_deploy:
  - openssl aes-256-cbc -K $encrypted_794da24f4770_key -iv $encrypted_794da24f4770_iv -in id_rsa_orthen_net.enc -out /tmp/id_rsa_orthen_net -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa_orthen_net
  - ssh-add /tmp/id_rsa_orthen_net

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
