language: nix


before_script:
  - rm -rf public 2> /dev/null

# script - run the build script
script:
  - nix-shell --run "hugo"

addons:
  ssh_known_hosts: orthen.net

before_deploy:
  - openssl aes-256-cbc -K $encrypted_dfd6ab479f24_key -iv $encrypted_dfd6ab479f24_iv -in id_ed25519_orthen_net.enc -out /tmp/id_ed25519_orthen_net -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_ed25519_orthen_net
  - ssh-add /tmp/id_ed25519_orthen_net

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
