baseURL = "https://orthen.net"
languageCode = "en-us"
title = "BO | HOME"
theme = "beautifulhugo"

defaultContentLanguage = "en"

# pygments
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Author]
  name = "Benjamin Orthen"
  website = "orthen.net"
  # email = "benjamin@orthen.net"
  # github = "benjaminor"

[[menu.main]]
	name = "Posts"
	url = "posts"
	weight = 1

[[menu.main]]
	name = "Contact"
	url = "contact"
	weight = 2

[[menu.main]]
	name = "Nextcloud"
	url = "https://nextcloud.orthen.net"
	weight=3
