baseurl = "https://orthen.net"

copyright = "All rights reserved - 2019"
languageCode = "en-US"
author = "Benjamin Orthen"
title = "Benjamin Orthen | HOME"
theme = "hugo-goa"
canonifyurls = true
paginate = 5

defaultContentLanguage = "en"

enableRobotsTXT = true

# pygments
# pygmentsStyle = "trac"
# pygmentsUseClasses = true
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true

# [Author]
#   name = "Benjamin Orthen"
#   website = "orthen.net"
#   email = "benjamin@orthen.net"
#   github = "benjaminor"


[params]
  author = "Benjamin Orthen"
  # authorlocation = "Munich, Germany"
  authorimage = "its_me.jpg"
  # description = "Whatever the mind of man can conceive and believe, it can achieve."
  # githubName = "benjaminor"
  intro = ""
  description = "Contact: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;benjamin (at) orthen.net<br/><br/> PGP-Key:	&nbsp;&nbsp;<a href=\"public_pgp_orthen.asc\">4D 1F C2 ED 78 57 DB 13</a>"
  dateformat = "02-Jan-2006"

[params.imagescaling]
## enabling image scaling for author image
authorimage200 = "its_me200.jpg"
authorimage800 = "its_me800.jpg"

## Site Meta Settings
[params.meta]
description = "Personal homepage"
keywords = "homepage, personal"

## Social Accounts
[params.social]
email = "benjamin@orthen.net"

## Extras
[params.extra]
copyright = "© 2019. Benjamin Orthen. All Rights Reserved."
poweredby = true
hightlightjs = true
rss = true

[[menu.main]]
	name = "Posts"
	url = "/posts"
	weight = 1

# [[menu.main]]
#	name = "Contact"
#	url = "/post/contact"
#	weight = 2

[[menu.main]]
	name = "Nextcloud"
	url = "https://nextcloud.orthen.net"
	weight= 3

[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
