name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - run: nix flake check
    - run: nix run .#hugo
    - uses: actions/upload-artifact@v2
      with:
        name: content
        path: public/
        retention-days: 7
      if: github.ref == 'refs/heads/master'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: content
      - run: ./deploy.sh
