name: "Deploy"
on:
  workflow_run:
    workflows: [Build]
    branches: [master]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: content
      - run: ./deploy.sh
